fix: input and select fill available space automatically
snaha-net/diete.design pull request #223
Opened 2024-05-29 10:55 UTC by hlavkat

resolve #208

2024-05-30 07:37 UTC, vojtechsimetka requested changes
Thanks, I think this is on the right path, but it breaks the component pages.

<img width="1174" alt="Screenshot 2024-05-30 at 9 34 21" src="https://github.com/diete-design/diete.design/assets/7974813/ba747c93-7c76-46ba-8c89-da787413c3b8">
<img width="1192" alt="Screenshot 2024-05-30 at 9 34 02" src="https://github.com/diete-design/diete.design/assets/7974813/b30141c5-0d4d-4920-975b-73918fdb56a0">

2024-06-05 09:37 UTC, vojtechsimetka approved these changes

2024-06-05 09:43 UTC, vojtechsimetka approved these changes

2024-06-05 12:19 UTC, agazso approved these changes
Works well for input, but for select it does not work everywhere. For example on the component page the examples should be automatically filling up horizontal space, but they don't. I would fix the select in another PR.

![Screenshot-20240605141748-2876x1554](https://github.com/diete-design/diete.design/assets/230163/cce20238-2b6f-4c79-8eac-b27737618e41)

2024-06-06 07:07 UTC, merged