feat: progress bar component
snaha-net/diete.design pull request #255
Opened 2024-06-06 08:43 UTC by hlavkat

2024-06-07 07:00 UTC, vojtechsimetka requested changes
- [ ] Build the component page
- [ ] Fix the font

2024-06-09 19:21 UTC, vojtechsimetka approved these changes
I think this is a good start and we could merge as is.

But it would be good to extend this component and allow setting custom `min` and `max` values as well as custom `unit`. Having just `%` covers quite a lot of use-cases but definitely not all. I'd suggest we do that in a separate PR.

2024-06-11 09:56 UTC, agazso commented on src/lib/components/ui/progress.svelte
> +		gap: 0.5rem;
Please use variables so that this can be customised.

```suggestion
		gap: var(--half-padding);
```

2024-06-11 09:59 UTC, agazso approved these changes

2024-06-11 14:40 UTC, merged