feat: rewrite Tooltip using popover api
snaha-net/diete.design pull request #274
Opened 2024-06-11 11:38 UTC by hlavkat

resolve #249

2024-06-13 09:43 UTC, agazso requested changes
Does not work correctly on Firefox.

Also the info icons don't appear in the correct color in dark mode.
![Screenshot_20240613_114214-1](https://github.com/snaha-net/diete.design/assets/230163/491ce3ef-2790-4aee-9132-a02c6687447a)

2024-06-13 19:40 UTC, agazso commented on src/lib/components/ui/tooltip.svelte
> +		tooltipName = 'tooltip',
Can this be randomised too?
```suggestion
		tooltipName = 'tooltip' + Math.random().toString(16),
```

2024-06-14 12:08 UTC, vojtechsimetka commented
Did I understood it correctly, that we ice this for now since the popover API is missing some crucial features in Mozilla?

2024-06-14 17:18 UTC, agazso commented
> Did I understood it correctly, that we ice this for now since the popover API is missing some crucial features in Mozilla?

Yes, that is my understanding. @hlavkat it would be good to document here what is the issue and close this PR.

2024-06-17 07:21 UTC, hlavkat commented
The Popover API has quite complex positioning that doesn't work in Firefox, it's a relatively new attribute and is still being developed, so we are waiting for upcoming improvements in positioning and for the popover attribute to mature further.

2024-06-17 07:21 UTC, closed without merging